import React, { useState, useEffect, useCallback, useRef } from 'react';

const API_BASE = '/api'; // v2025-06-17-refresh

/* ─── Simple markdown renderer (no external deps) ─── */
function mdToHtml(text) {
  if (!text) return '';
  const esc = (s) => s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
  const lines = text.split('\n');
  let html = '';
  let inList = false;
  let inCode = false;
  let codeBuf = '';
  let codeLang = '';

  const flushList = () => { if (inList) { html += '</ul>'; inList = false; } };
  const startList = () => { if (!inList) { html += '<ul>'; inList = true; } };

  for (let raw of lines) {
    const line = raw; // keep original for code blocks

    // Code fences
    if (line.startsWith('```')) {
      if (inCode) {
        html += `<pre style="background:#0a0a14;padding:12px;border-radius:6px;overflow:auto;font-size:13px;border:1px solid #1e1e2e;margin:8px 0"><code>${esc(codeBuf)}</code></pre>`;
        codeBuf = '';
        inCode = false;
        continue;
      }
      inCode = true;
      codeLang = line.slice(3).trim();
      flushList();
      continue;
    }
    if (inCode) {
      codeBuf += line + '\n';
      continue;
    }

    // Headings
    const h1 = line.match(/^#\s+(.+)$/);
    const h2 = line.match(/^##\s+(.+)$/);
    const h3 = line.match(/^###\s+(.+)$/);
    if (h1) { flushList(); html += `<h1 style="font-size:22px;margin:18px 0 10px;color:#f8fafc;font-weight:700">${renderInline(h1[1])}</h1>`; continue; }
    if (h2) { flushList(); html += `<h2 style="font-size:18px;margin:16px 0 8px;color:#f8fafc;font-weight:600;border-bottom:1px solid #1e1e2e;padding-bottom:4px">${renderInline(h2[1])}</h2>`; continue; }
    if (h3) { flushList(); html += `<h3 style="font-size:15px;margin:12px 0 6px;color:#e2e2e2;font-weight:600">${renderInline(h3[1])}</h3>`; continue; }

    // Blockquote
    if (line.startsWith('> ')) {
      flushList();
      html += `<blockquote style="border-left:3px solid #3b82f6;padding-left:10px;margin:8px 0;color:#94a3b8">${renderInline(line.slice(2))}</blockquote>`;
      continue;
    }

    // List items
    if (line.match(/^[-*]\s/)) {
      startList();
      html += `<li style="margin:3px 0">${renderInline(line.replace(/^[-*]\s+/, ''))}</li>`;
      continue;
    }
    flushList();

    // Empty line
    if (!line.trim()) {
      html += '<br/>';
      continue;
    }

    // Horizontal rule
    if (line.match(/^---+$/)) {
      html += '<hr style="border:none;border-top:1px solid #1e1e2e;margin:12px 0"/>';
      continue;
    }

    // Regular paragraph
    html += `<p style="margin:6px 0;line-height:1.7">${renderInline(line)}</p>`;
  }
  flushList();
  return html;
}

function renderInline(text) {
  return text
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/`([^`]+)`/g, '<code style="background:#1e1e2e;padding:1px 4px;border-radius:3px;font-size:13px">$1</code>')
    .replace(/\[\[([^\]]+)\]\]/g, '<a href="#" style="color:#60a5fa;text-decoration:none" onclick="return false">$1</a>')
    .replace(/#([a-zA-Z0-9_-]+)/g, '<span style="color:#f472b6">#$1</span>');
}

/* ─── TOC extraction ─── */
function extractToc(text) {
  const items = [];
  const lines = text.split('\n');
  for (const line of lines) {
    const m2 = line.match(/^##\s+(.+)/);
    const m3 = line.match(/^###\s+(.+)/);
    if (m2) items.push({ text: m2[1].replace(/\*\*/g,'').trim(), level: 2 });
    else if (m3) items.push({ text: m3[1].replace(/\*\*/g,'').trim(), level: 3 });
  }
  return items;
}

/* ─── Main Component ─── */
export default function WikiPage({ onBack }) {
  const [view, setView] = useState('split'); // split | edit | preview
  const [editorText, setEditorText] = useState(`# Welcome to OtterWiki\n\nThis is your personal wiki powered by local AI.\n\n## Getting Started\n\n- Use the **AI Writer** panel to generate content\n- Edit markdown directly in the editor\n- Preview renders your markdown in real-time\n\n## Example\n\n\`\`\`javascript\n// Generated by AI\nconsole.log("Hello, wiki!");\n\`\`\`\n\n> \"Knowledge is power.\"\n\n## Related\n\n- [[Getting Started]]\n- [[Contributing]]\n\n#wiki #ai`);
  const [docs, setDocs] = useState([]);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedDoc, setSelectedDoc] = useState(null);
  const [aiOpen, setAiOpen] = useState(true);
  const [aiPrompt, setAiPrompt] = useState('');
  const [aiTitle, setAiTitle] = useState('');
  const [aiLoading, setAiLoading] = useState(false);
  const [saveStatus, setSaveStatus] = useState('');
  const [saveTitle, setSaveTitle] = useState('');
  const [saveCategory, setSaveCategory] = useState('concepts');
  const [rewriteStyle, setRewriteStyle] = useState('concise');
  const [toc, setToc] = useState([]);
  const editorRef = useRef(null);

  // Inline toolbar
  const [selStart, setSelStart] = useState(0);
  const [selEnd, setSelEnd] = useState(0);
  const [showInline, setShowInline] = useState(false);
  const [inlinePos, setInlinePos] = useState({ top: 0, left: 0 });

  // AI panel tabs
  const [aiTab, setAiTab] = useState('generate'); // generate | edit | draft | analyze | ingest | auto
  const [analysis, setAnalysis] = useState(null);
  const [draftOutline, setDraftOutline] = useState('');

  // Autoresearch
  const [autoTopic, setAutoTopic] = useState('');
  const [autoRunning, setAutoRunning] = useState(false);
  const [autoIntervalRef, setAutoIntervalRef] = useState(null);
  const [autoStatus, setAutoStatus] = useState('');

  // File drop
  const [dropHover, setDropHover] = useState(false);
  const [dropFiles, setDropFiles] = useState([]);

  // Integration status
  const [sysStatus, setSysStatus] = useState(null);

  // Swarm
  const [swarmTopic, setSwarmTopic] = useState('');
  const [swarmInvite, setSwarmInvite] = useState('');
  const [swarmPeers, setSwarmPeers] = useState(0);
  const [swarmTopics, setSwarmTopics] = useState([]);
  const [joinTopicInput, setJoinTopicInput] = useState('');
  const [swarmScope, setSwarmScope] = useState('wiki'); // 'wiki' | 'page'

  useEffect(() => { fetchDocs(); fetchStatus(); }, []);
  useEffect(() => { setToc(extractToc(editorText)); }, [editorText]);
  useEffect(() => () => { if (autoIntervalRef) clearInterval(autoIntervalRef); }, []);

  const fetchStatus = async () => {
    try {
      const res = await fetch(`${API_BASE}/wiki-status`);
      const json = await res.json();
      if (json.success) setSysStatus(json.data);
    } catch (e) { console.error(e); }
  };

  const fetchSwarmStatus = async () => {
    try {
      const res = await fetch(`${API_BASE}/swarm/status`);
      const json = await res.json();
      if (json.success && json.data) {
        setSwarmPeers(json.data.peers || 0);
        setSwarmTopics(json.data.topics || []);
      }
    } catch (e) { console.error(e); }
  };

  const createSwarm = async () => {
    setSaveStatus('Creating swarm...');
    const pageId = selectedDoc || null;
    const pageTitle = pageId ? docs.find(d => d.id === pageId)?.title : null;
    try {
      const res = await fetch(`${API_BASE}/swarm/create`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ scope: swarmScope, pageId, pageTitle })
      });
      const json = await res.json();
      if (json.success) {
        setSwarmTopic(json.data.topic);
        setSwarmInvite(json.data.inviteUrl);
        setSaveStatus(swarmScope === 'page' ? 'Page swarm created!' : 'Wiki swarm created!');
        fetchSwarmStatus();
      } else {
        setSaveStatus('Failed');
      }
    } catch (e) {
      console.error(e);
      setSaveStatus('Failed');
    }
    setTimeout(() => setSaveStatus(''), 3000);
  };

  const joinSwarm = async () => {
    if (!joinTopicInput.trim()) return;
    setSaveStatus('Joining swarm...');
    try {
      const res = await fetch(`${API_BASE}/swarm/join`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ topic: joinTopicInput.trim() })
      });
      const json = await res.json();
      if (json.success) {
        setSwarmTopic(json.data.topic);
        setSaveStatus('Joined!');
        setJoinTopicInput('');
        fetchSwarmStatus();
      } else {
        setSaveStatus('Join failed');
      }
    } catch (e) {
      console.error(e);
      setSaveStatus('Join failed');
    }
    setTimeout(() => setSaveStatus(''), 3000);
  };

  const fetchDocs = async () => {
    try {
      const res = await fetch(`${API_BASE}/llmwiki-docs`);
      const json = await res.json();
      if (json.success) setDocs(json.data || []);
    } catch (e) {
      console.error('Failed to fetch docs:', e);
    }
  };

  const handleGenerate = async () => {
    if (!aiPrompt.trim()) return;
    setAiLoading(true);
    try {
      const res = await fetch(`${API_BASE}/ai-write`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt: aiPrompt, title: aiTitle || undefined })
      });
      const json = await res.json();
      if (json.success) {
        const generated = json.data.body;
        setEditorText(prev => {
          const sep = prev.trim().length > 0 ? '\n\n---\n\n' : '';
          return prev + sep + generated;
        });
        setAiPrompt('');
        setAiTitle('');
      }
    } catch (e) {
      console.error(e);
    } finally {
      setAiLoading(false);
    }
  };

  const handleSave = async () => {
    if (!editorText.trim()) return;
    const title = saveTitle.trim() || (editorText.match(/^#\s+(.+)$/m)?.[1] || 'Untitled');
    setSaveStatus('Saving...');
    try {
      const res = await fetch(`${API_BASE}/llmwiki-save`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ content: editorText, title, category: saveCategory })
      });
      const json = await res.json();
      if (json.success) {
        setSaveStatus('Saved!');
        setSaveTitle('');
        await fetchDocs();
        setTimeout(() => setSaveStatus(''), 2000);
      } else {
        setSaveStatus('Save failed');
      }
    } catch (e) {
      console.error(e);
      setSaveStatus('Save failed');
    }
  };

  const handleRewrite = async () => {
    const ta = editorRef.current;
    if (!ta) return;
    const start = ta.selectionStart;
    const end = ta.selectionEnd;
    const selected = editorText.slice(start, end);
    if (!selected.trim()) {
      setSaveStatus('Select text first');
      setTimeout(() => setSaveStatus(''), 2000);
      return;
    }

    setAiLoading(true);
    setSaveStatus('Rewriting...');
    try {
      const style = rewriteStyle.trim() || 'concise';
      const prompt = `Rewrite the following text in a ${style} style. Output ONLY the rewritten text — no preamble, no explanation, no markdown fences unless the original had them.\n\nOriginal text:\n${selected}`;
      const res = await fetch(`${API_BASE}/ai-write`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt })
      });
      const json = await res.json();
      if (json.success) {
        const rewritten = json.data.body.trim();
        const before = editorText.slice(0, start);
        const after = editorText.slice(end);
        setEditorText(before + rewritten + after);
        setSaveStatus('Rewritten!');
        setTimeout(() => { setSaveStatus(''); ta.selectionStart = start; ta.selectionEnd = start + rewritten.length; ta.focus(); }, 50);
      } else {
        setSaveStatus('Rewrite failed');
      }
    } catch (e) {
      console.error(e);
      setSaveStatus('Rewrite failed');
    } finally {
      setAiLoading(false);
    }
  };

  const trackSelection = () => {
    const ta = editorRef.current;
    if (!ta) return;
    const start = ta.selectionStart;
    const end = ta.selectionEnd;
    setSelStart(start);
    setSelEnd(end);
    if (start !== end) {
      const rect = ta.getBoundingClientRect();
      // approximate position above selection
      setInlinePos({ top: rect.top + window.scrollY - 38, left: rect.left + window.scrollX + 10 });
      setShowInline(true);
    } else {
      setShowInline(false);
    }
  };

  const aiAction = async (instruction, type = 'replace') => {
    const selected = editorText.slice(selStart, selEnd);
    if (!selected.trim()) {
      setSaveStatus('Select text first');
      setTimeout(() => setSaveStatus(''), 2000);
      return;
    }
    setAiLoading(true);
    setSaveStatus(type === 'analyze' ? 'Analyzing...' : 'Processing...');
    try {
      const prompt = `${instruction}\n\nText:\n${selected}`;
      const res = await fetch(`${API_BASE}/ai-write`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt })
      });
      const json = await res.json();
      if (json.success) {
        const result = json.data.body.trim();
        if (type === 'replace') {
          const before = editorText.slice(0, selStart);
          const after = editorText.slice(selEnd);
          setEditorText(before + result + after);
          setSaveStatus('Done!');
          setTimeout(() => setSaveStatus(''), 1500);
        } else if (type === 'append') {
          const before = editorText.slice(0, selEnd);
          const after = editorText.slice(selEnd);
          setEditorText(before + '\n\n' + result + after);
          setSaveStatus('Done!');
          setTimeout(() => setSaveStatus(''), 1500);
        } else if (type === 'analyze') {
          setAnalysis(result);
          setSaveStatus('');
        }
        setShowInline(false);
      } else {
        setSaveStatus('Failed');
      }
    } catch (e) {
      console.error(e);
      setSaveStatus('Failed');
    } finally {
      setAiLoading(false);
    }
  };

  // ─── Autoresearch ───
  const startAutoresearch = () => {
    if (!autoTopic.trim()) return;
    setAutoRunning(true);
    setAutoStatus('Autoresearch running...');
    let count = 0;
    const id = setInterval(async () => {
      count++;
      setAutoStatus(`Researching... (cycle ${count})`);
      try {
        const res = await fetch(`${API_BASE}/ai-write`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ prompt: `Research and write a new wiki section about: ${autoTopic}. Add depth, new angles, or related subtopics. Output ONLY markdown content.` })
        });
        const json = await res.json();
        if (json.success) {
          const generated = json.data.body;
          setEditorText(prev => {
            const sep = prev.trim().length > 0 ? '\n\n---\n\n' : '';
            return prev + sep + `## Auto-Research: ${autoTopic} (Cycle ${count})\n\n` + generated;
          });
        }
      } catch (e) { console.error(e); }
    }, 30000); // every 30 seconds
    setAutoIntervalRef(id);
  };

  const stopAutoresearch = () => {
    if (autoIntervalRef) clearInterval(autoIntervalRef);
    setAutoIntervalRef(null);
    setAutoRunning(false);
    setAutoStatus('Autoresearch stopped');
    setTimeout(() => setAutoStatus(''), 2000);
  };

  // ─── Drag & Drop ───
  const handleDragOver = (e) => { e.preventDefault(); setDropHover(true); };
  const handleDragLeave = (e) => { e.preventDefault(); setDropHover(false); };
  const handleDrop = async (e) => {
    e.preventDefault();
    setDropHover(false);
    const files = Array.from(e.dataTransfer.files);
    if (!files.length) return;
    setDropFiles(files.map(f => ({ name: f.name, size: f.size, status: 'uploading' })));
    setSaveStatus('Converting to markdown...');

    for (const file of files) {
      const formData = new FormData();
      formData.append('file', file);
      try {
        const res = await fetch(`${API_BASE}/convert-to-md`, { method: 'POST', body: formData });
        const json = await res.json();
        if (json.success) {
          setDropFiles(prev => prev.map(f => f.name === file.name ? { ...f, status: 'done' } : f));
          const md = json.data.markdown || '';
          setEditorText(prev => {
            const sep = prev.trim().length > 0 ? '\n\n---\n\n' : '';
            return prev + sep + `## Source: ${file.name}\n\n${md}\n`;
          });
        } else {
          setDropFiles(prev => prev.map(f => f.name === file.name ? { ...f, status: 'failed' } : f));
        }
      } catch (err) {
        setDropFiles(prev => prev.map(f => f.name === file.name ? { ...f, status: 'failed' } : f));
      }
    }
    setSaveStatus('Files converted');
    setTimeout(() => setSaveStatus(''), 3000);
  };

  const insertAtCursor = (text) => {
    const ta = editorRef.current;
    if (!ta) return;
    const start = ta.selectionStart;
    const end = ta.selectionEnd;
    const before = editorText.slice(0, start);
    const after = editorText.slice(end);
    setEditorText(before + text + after);
    setTimeout(() => { ta.selectionStart = ta.selectionEnd = start + text.length; ta.focus(); }, 0);
  };

  const filteredDocs = docs.filter(d =>
    (d.title || '').toLowerCase().includes(searchQuery.toLowerCase()) ||
    (d.category || '').toLowerCase().includes(searchQuery.toLowerCase())
  );

  const groupedDocs = filteredDocs.reduce((acc, d) => {
    const cat = d.category || '.';
    if (!acc[cat]) acc[cat] = [];
    acc[cat].push(d);
    return acc;
  }, {});

  const toolbarBtn = (label, action) => (
    <button key={label} style={s.toolbarBtn} onClick={action} title={label}>
      {label}
    </button>
  );

  return (
    <div style={s.layout}>
      {/* ─── Left Sidebar ─── */}
      <aside style={s.sidebar}>
        <div style={s.sidebarHeader}>
          <span style={s.logo}>⚡ Chimera</span>
        </div>
        {onBack && (
          <button style={s.backBtn} onClick={onBack}>← Back</button>
        )}
        <div style={s.searchBox}>
          <input
            style={s.searchInput}
            placeholder="Search pages..."
            value={searchQuery}
            onChange={e => setSearchQuery(e.target.value)}
          />
        </div>
        <div style={s.navHeader}>Outline</div>
        <nav style={s.nav}>
          {Object.entries(groupedDocs).sort((a,b) => a[0].localeCompare(b[0])).map(([cat, items]) => (
            <div key={cat}>
              <div style={s.navCategory}>{cat === '.' ? 'Root' : cat}</div>
              {items.map(doc => (
                <div
                  key={doc.id}
                  style={selectedDoc === doc.id ? s.navItemActive : s.navItem}
                  onClick={() => {
                    setSelectedDoc(doc.id);
                    setEditorText(doc.body || `# ${doc.title}\n\n(No content loaded)`);
                  }}
                >
                  <span style={s.navIcon}>📄</span>
                  <span style={s.navTitle}>{doc.title}</span>
                </div>
              ))}
            </div>
          ))}
          {docs.length === 0 && (
            <div style={s.emptyNav}>No wiki pages yet.<br/>Generate one with AI →</div>
          )}
        </nav>
        <div style={{ padding: '10px 12px', borderTop: '1px solid #1e1e2e', borderBottom: '1px solid #1e1e2e', display: 'flex', flexDirection: 'column', gap: 6 }}>
          <div style={{ fontSize: 10, color: '#64748b', fontWeight: 600, textTransform: 'uppercase', letterSpacing: 0.6 }}>Hyperswarm</div>

          {/* Scope selector */}
          <div style={{ display: 'flex', gap: 2, background: '#1e1e2e', borderRadius: 4, padding: 2 }}>
            <button
              style={{ flex: 1, padding: '3px 6px', fontSize: 10, borderRadius: 3, border: 'none', cursor: 'pointer', background: swarmScope === 'wiki' ? '#0a0a14' : 'transparent', color: swarmScope === 'wiki' ? '#e2e2e2' : '#94a3b8' }}
              onClick={() => setSwarmScope('wiki')}
            >
              Entire Wiki
            </button>
            <button
              style={{ flex: 1, padding: '3px 6px', fontSize: 10, borderRadius: 3, border: 'none', cursor: 'pointer', background: swarmScope === 'page' ? '#0a0a14' : 'transparent', color: swarmScope === 'page' ? '#e2e2e2' : '#94a3b8' }}
              onClick={() => setSwarmScope('page')}
            >
              This Page
            </button>
          </div>
          {swarmScope === 'page' && !selectedDoc && (
            <div style={{ fontSize: 9, color: '#fca5a5' }}>⚠ Select a page in the outline first</div>
          )}
          {swarmScope === 'page' && selectedDoc && (
            <div style={{ fontSize: 9, color: '#86efac' }}>📄 {docs.find(d => d.id === selectedDoc)?.title || 'Current page'}</div>
          )}

          <button style={{ ...s.newPageBtn, background: '#dc2626', color: '#fff', borderColor: '#b91c1c' }} onClick={createSwarm}>
            🌐 Create {swarmScope === 'page' ? 'Page' : 'Wiki'} Swarm
          </button>
          {swarmTopic && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
              <div style={{ fontSize: 10, color: '#86efac' }}>Topic: {swarmTopic.slice(0, 20)}...</div>
              <button
                style={{ ...s.toolbarBtn, fontSize: 9, padding: '3px 6px' }}
                onClick={() => { navigator.clipboard.writeText(swarmTopic); setSaveStatus('Copied!'); setTimeout(() => setSaveStatus(''), 1500); }}
              >
                📋 Copy Topic
              </button>
            </div>
          )}
          <div style={{ display: 'flex', gap: 4 }}>
            <input
              style={{ ...s.searchInput, flex: 1, fontSize: 11 }}
              placeholder="Paste topic hex..."
              value={joinTopicInput}
              onChange={e => setJoinTopicInput(e.target.value)}
            />
            <button style={{ ...s.toolbarBtn, padding: '4px 8px', fontSize: 10 }} onClick={joinSwarm}>Join</button>
          </div>
          {swarmPeers > 0 && (
            <div style={{ fontSize: 10, color: '#86efac' }}>🟢 {swarmPeers} peer{swarmPeers !== 1 ? 's' : ''} connected</div>
          )}
          {swarmTopics.length > 0 && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
              {swarmTopics.map((t, i) => (
                <div key={i} style={{ fontSize: 9, color: t.scope === 'page' ? '#fca5a5' : '#94a3b8' }}>
                  • {t.scope === 'page' ? '📄' : '🌐'} {t.short} {t.title ? `(${t.title})` : ''}
                </div>
              ))}
            </div>
          )}
        </div>
        <div style={{ padding: '10px 12px', borderTop: '1px solid #1e1e2e', borderBottom: '1px solid #1e1e2e', display: 'flex', flexDirection: 'column', gap: 6 }}>
          <div style={{ fontSize: 10, color: '#64748b', fontWeight: 600, textTransform: 'uppercase', letterSpacing: 0.6 }}>Openviking Memory</div>
          <div style={{ fontSize: 10, color: '#86efac', lineHeight: 1.5 }}>
            AI memory store via REST API
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
            <button
              style={{ ...s.toolbarBtn, fontSize: 9, padding: '3px 6px', textAlign: 'left' }}
              onClick={() => navigator.clipboard.writeText(`${window.location.origin}/api/llmwiki-docs`)}
            >
              📋 Copy docs endpoint
            </button>
            <button
              style={{ ...s.toolbarBtn, fontSize: 9, padding: '3px 6px', textAlign: 'left' }}
              onClick={() => navigator.clipboard.writeText(`${window.location.origin}/api/llmwiki-search?q=`)}
            >
              📋 Copy search endpoint
            </button>
            <button
              style={{ ...s.toolbarBtn, fontSize: 9, padding: '3px 6px', textAlign: 'left' }}
              onClick={() => navigator.clipboard.writeText(`${window.location.origin}/api/llmwiki-graph?id=`)}
            >
              📋 Copy graph endpoint
            </button>
          </div>
          <details style={{ fontSize: 10, color: '#94a3b8' }}>
            <summary style={{ cursor: 'pointer', color: '#64748b', fontWeight: 600 }}>How to connect an AI</summary>
            <div style={{ padding: '6px 0', display: 'flex', flexDirection: 'column', gap: 4, lineHeight: 1.5 }}>
              <div><b style={{ color: '#e2e2e2' }}>1. Search</b><br/>GET /api/llmwiki-search?q={'{query}'}</div>
              <div><b style={{ color: '#e2e2e2' }}>2. Read</b><br/>GET /api/llmwiki-docs</div>
              <div><b style={{ color: '#e2e2e2' }}>3. Graph</b><br/>GET /api/llmwiki-graph?id={'{pageId}'}</div>
              <div style={{ color: '#64748b', fontSize: 9, marginTop: 2 }}>
                Use these endpoints in your AI agent's tool calls. The wiki becomes a persistent, queryable memory store that syncs across the P2P swarm.
              </div>
            </div>
          </details>
        </div>
        <div style={s.sidebarFooter}>
          <button style={s.newPageBtn} onClick={() => { setSelectedDoc(null); setEditorText(''); }}>
            + New Page
          </button>
        </div>
      </aside>

      {/* ─── Main Content ─── */}
      <main style={s.main}>
        {/* Toolbar */}
        <div style={s.toolbar}>
          <div style={s.toolbarGroup}>
            {toolbarBtn('H1', () => insertAtCursor('# '))}
            {toolbarBtn('H2', () => insertAtCursor('## '))}
            {toolbarBtn('H3', () => insertAtCursor('### '))}
            {toolbarBtn('Bold', () => insertAtCursor('**text**'))}
            {toolbarBtn('Italic', () => insertAtCursor('*text*'))}
            {toolbarBtn('Code', () => insertAtCursor('`code`'))}
            {toolbarBtn('Link', () => insertAtCursor('[[Page]]'))}
            {toolbarBtn('List', () => insertAtCursor('- item\n'))}
            {toolbarBtn('Quote', () => insertAtCursor('> quote\n'))}
            {toolbarBtn('Rule', () => insertAtCursor('\n---\n'))}
          </div>
          <div style={s.toolbarGroup}>
            <button style={view === 'edit' ? s.modeBtnActive : s.modeBtn} onClick={() => setView('edit')}>Edit</button>
            <button style={view === 'split' ? s.modeBtnActive : s.modeBtn} onClick={() => setView('split')}>Split</button>
            <button style={view === 'preview' ? s.modeBtnActive : s.modeBtn} onClick={() => setView('preview')}>Preview</button>
          </div>
          <div style={s.toolbarGroup}>
            <button style={{ ...s.toolbarBtn, background: '#166534', color: '#86efac', borderColor: '#166534' }} onClick={handleSave}>
              💾 Save
            </button>
            {saveStatus && <span style={{ fontSize: 12, color: '#94a3b8' }}>{saveStatus}</span>}
          </div>
        </div>

        {/* Editor + Preview */}
        <div
          style={s.editorPane}
          onDragOver={handleDragOver}
          onDragLeave={handleDragLeave}
          onDrop={handleDrop}
        >
          {dropHover && (
            <div style={{ position: 'absolute', inset: 0, background: 'rgba(59,130,246,0.1)', border: '2px dashed #3b82f6', zIndex: 50, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 16, color: '#3b82f6' }}>
              Drop PDFs, links, or files here to analyze
            </div>
          )}
          {(view === 'edit' || view === 'split') && (
            <div style={view === 'split' ? s.splitLeft : s.full}>
              <textarea
                ref={editorRef}
                style={s.textarea}
                value={editorText}
                onChange={e => { setShowInline(false); setEditorText(e.target.value); }}
                onMouseUp={trackSelection}
                onKeyUp={trackSelection}
                spellCheck={false}
                placeholder="Start writing markdown..."
              />
            </div>
          )}
          {(view === 'preview' || view === 'split') && (
            <div style={view === 'split' ? s.splitRight : s.full}>
              <div style={s.preview} dangerouslySetInnerHTML={{ __html: mdToHtml(editorText) }} />
              {toc.length > 0 && (
                <div style={s.toc}>
                  <div style={s.tocTitle}>Contents</div>
                  {toc.map((item, i) => (
                    <div key={i} style={item.level === 3 ? s.tocItem3 : s.tocItem}>
                      {item.text}
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}
        </div>
      </main>

      {/* ─── Inline Selection Toolbar ─── */}
      {showInline && (
        <div style={{ position: 'fixed', top: inlinePos.top, left: inlinePos.left, zIndex: 100, display: 'flex', gap: 4, padding: '4px 6px', background: '#1e1e2e', border: '1px solid #2e2e3e', borderRadius: 6, boxShadow: '0 4px 12px rgba(0,0,0,0.4)' }}>
          <button style={s.inlineBtn} onClick={() => aiAction('Rewrite the following text to be more concise. Output ONLY the rewritten text.', 'replace')}>Shorten</button>
          <button style={s.inlineBtn} onClick={() => aiAction('Expand the following text with more detail and examples. Output ONLY the expanded text.', 'replace')}>Expand</button>
          <button style={s.inlineBtn} onClick={() => aiAction('Fix grammar and improve clarity of the following text. Output ONLY the corrected text.', 'replace')}>Fix</button>
          <button style={s.inlineBtn} onClick={() => aiAction('Rewrite the following text to be more formal. Output ONLY the rewritten text.', 'replace')}>Formal</button>
          <button style={s.inlineBtn} onClick={() => aiAction('Continue writing from the end of the following text. Output ONLY the continuation.', 'append')}>Continue</button>
          <button style={s.inlineBtn} onClick={() => aiAction('Explain why this text is weak and suggest improvements. Output ONLY the critique.', 'analyze')}>Critique</button>
        </div>
      )}

      {/* ─── Right AI Panel ─── */}
      <aside style={aiOpen ? s.aiPanel : s.aiPanelCollapsed}>
        <div style={s.aiHeader} onClick={() => setAiOpen(!aiOpen)}>
          <span>🤖 AI Writer</span>
          <span style={s.aiToggle}>{aiOpen ? '›' : '‹'}</span>
        </div>
        {aiOpen && (
          <div style={s.aiBody}>
            {/* Tabs */}
            <div style={{ display: 'flex', gap: 3, borderBottom: '1px solid #1e1e2e', paddingBottom: 8 }}>
              {['generate','edit','draft','analyze','ingest','auto'].map(tab => (
                <button
                  key={tab}
                  onClick={() => setAiTab(tab)}
                  style={{
                    padding: '4px 8px',
                    borderRadius: 4,
                    fontSize: 10,
                    cursor: 'pointer',
                    whiteSpace: 'nowrap',
                    flexShrink: 0,
                    ...(tab === 'auto'
                      ? { background: aiTab === tab ? '#dc2626' : '#450a0a', color: aiTab === tab ? '#fff' : '#fca5a5', border: '1px solid #b91c1c' }
                      : aiTab === tab
                        ? { background: '#0a0a14', color: '#e2e2e2', border: '1px solid #3e3e4e' }
                        : { background: '#1e1e2e', color: '#94a3b8', border: '1px solid #2e2e3e' }
                    )
                  }}
                >
                  {tab === 'auto' ? 'Auto' : tab[0].toUpperCase() + tab.slice(1)}
                </button>
              ))}
            </div>

            {/* ── Generate Tab ── */}
            {aiTab === 'generate' && (
              <>
                <div style={s.aiField}>
                  <label style={s.aiLabel}>Topic / Prompt</label>
                  <textarea style={s.aiTextarea} rows={3} value={aiPrompt} onChange={e => setAiPrompt(e.target.value)} placeholder="Write about distributed systems..." />
                </div>
                <div style={s.aiField}>
                  <label style={s.aiLabel}>Page Title (optional)</label>
                  <input style={s.aiInput} value={aiTitle} onChange={e => setAiTitle(e.target.value)} placeholder="Auto-generated" />
                </div>
                <button style={s.aiBtn} onClick={handleGenerate} disabled={aiLoading || !aiPrompt.trim()}>
                  {aiLoading ? 'Generating...' : 'Generate & Insert'}
                </button>
              </>
            )}

            {/* ── Edit Tab ── */}
            {aiTab === 'edit' && (
              <>
                <div style={s.aiField}>
                  <label style={s.aiLabel}>Style</label>
                  <select style={s.aiInput} value={rewriteStyle} onChange={e => setRewriteStyle(e.target.value)}>
                    <option value="concise">concise</option>
                    <option value="formal">formal</option>
                    <option value="casual">casual</option>
                    <option value="technical">technical</option>
                    <option value="poetic">poetic</option>
                    <option value="expand">expand</option>
                    <option value="summarize">summarize</option>
                  </select>
                </div>
                <button style={{ ...s.aiBtn, background: '#8b5cf6' }} onClick={handleRewrite} disabled={aiLoading}>
                  {aiLoading ? 'Rewriting...' : '✏️ Rewrite Selection'}
                </button>
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginTop: 8 }}>
                  {[
                    ['Shorten','Rewrite more concisely'],
                    ['Expand','Add detail and examples'],
                    ['Simplify','Make it simpler'],
                    ['Grammar','Fix grammar & clarity'],
                    ['Formal','Make formal'],
                    ['Casual','Make casual'],
                    ['Bullets','Convert to bullet points'],
                    ['Paragraph','Convert to paragraph'],
                    ['3 Alt','Give 3 alternatives'],
                    ['Explain','Explain why weak'],
                  ].map(([label, instruction]) => (
                    <button key={label} style={s.miniBtn} onClick={() => aiAction(`${instruction}. Output ONLY the result.`, label === '3 Alt' || label === 'Explain' ? 'analyze' : 'replace')} disabled={aiLoading}>
                      {label}
                    </button>
                  ))}
                </div>
                <div style={s.aiHint}>Highlight text in the editor, then click an action.</div>
              </>
            )}

            {/* ── Draft Tab ── */}
            {aiTab === 'draft' && (
              <>
                <div style={s.aiField}>
                  <label style={s.aiLabel}>Outline Topic</label>
                  <input style={s.aiInput} value={draftOutline} onChange={e => setDraftOutline(e.target.value)} placeholder="e.g. Blockchain consensus" />
                </div>
                <button style={s.aiBtn} onClick={() => {
                  if (!draftOutline.trim()) return;
                  aiAction(`Create a numbered outline for: ${draftOutline}. Output ONLY the outline.`, 'append');
                }} disabled={aiLoading || !draftOutline.trim()}>
                  Generate Outline
                </button>
                <div style={{ borderTop: '1px solid #1e1e2e', marginTop: 8, paddingTop: 8, display: 'flex', flexDirection: 'column', gap: 6 }}>
                  <span style={s.aiLabel}>Section Writer</span>
                  {['Write intro','Write conclusion','Add objections','Add examples'].map(label => (
                    <button key={label} style={s.miniBtn} onClick={() => aiAction(`${label} based on the current document. Output ONLY the new section.`, 'append')} disabled={aiLoading}>
                      {label}
                    </button>
                  ))}
                </div>
                <div style={{ borderTop: '1px solid #1e1e2e', marginTop: 8, paddingTop: 8 }}>
                  <button style={s.miniBtn} onClick={() => aiAction('Summarize the current document into a TL;DR paragraph. Output ONLY the summary.', 'append')} disabled={aiLoading}>
                    TL;DR Summary
                  </button>
                  <button style={s.miniBtn} onClick={() => aiAction('Convert the current document into a clean set of bullet points. Output ONLY the bullets.', 'replace')} disabled={aiLoading}>
                    Notes to Bullets
                  </button>
                </div>
              </>
            )}

            {/* ── Analyze Tab ── */}
            {aiTab === 'analyze' && (
              <>
                <button style={s.aiBtn} onClick={() => aiAction('Analyze the tone of the following text and describe it in one sentence (e.g. formal, casual, technical, persuasive). Output ONLY the tone description.', 'analyze')} disabled={aiLoading}>
                  Detect Tone
                </button>
                <button style={s.aiBtn} onClick={() => aiAction('Estimate the reading level and readability of the following text (Flesch Reading Ease score and grade level). Output ONLY the score and brief assessment.', 'analyze')} disabled={aiLoading}>
                  Readability Score
                </button>
                <button style={s.aiBtn} onClick={() => aiAction('Flag any overused phrases, repetitions, weak claims, or inconsistencies in the following text. Output ONLY the findings.', 'analyze')} disabled={aiLoading}>
                  Weakness Scan
                </button>
                {analysis && (
                  <div style={{ background: '#0a0a14', border: '1px solid #1e1e2e', borderRadius: 5, padding: 10, fontSize: 12, color: '#94a3b8', lineHeight: 1.6, whiteSpace: 'pre-wrap', marginTop: 4 }}>
                    {analysis}
                  </div>
                )}
              </>
            )}

            {/* ── Ingest Tab ── */}
            {aiTab === 'ingest' && (
              <>
                <div style={{ padding: '8px', background: '#0a0a14', border: '1px dashed #2e2e3e', borderRadius: 5, textAlign: 'center', fontSize: 12, color: '#64748b' }}>
                  <div>Drag & drop files onto the editor</div>
                  <div style={{ fontSize: 10, marginTop: 4 }}>PDFs, Word, PowerPoint, images, HTML → Markdown</div>
                </div>
                <div style={s.aiField}>
                  <label style={s.aiLabel}>Or browse files</label>
                  <input
                    type="file"
                    style={{ fontSize: 11, color: '#94a3b8' }}
                    onChange={async (e) => {
                      const file = e.target.files?.[0];
                      if (!file) return;
                      setSaveStatus('Converting...');
                      const formData = new FormData();
                      formData.append('file', file);
                      try {
                        const res = await fetch(`${API_BASE}/convert-to-md`, { method: 'POST', body: formData });
                        const json = await res.json();
                        if (json.success) {
                          const md = json.data.markdown || '';
                          setEditorText(prev => {
                            const sep = prev.trim().length > 0 ? '\n\n---\n\n' : '';
                            return prev + sep + `## Source: ${file.name}\n\n${md}\n`;
                          });
                          setSaveStatus('Inserted!');
                        } else {
                          setSaveStatus('Conversion failed');
                        }
                      } catch (err) {
                        setSaveStatus('Conversion failed');
                      }
                      setTimeout(() => setSaveStatus(''), 3000);
                    }}
                  />
                </div>
                {dropFiles.length > 0 && (
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
                    {dropFiles.map((f, i) => (
                      <div key={i} style={{ fontSize: 11, color: f.status === 'done' ? '#86efac' : f.status === 'failed' ? '#f87171' : '#94a3b8' }}>
                        {f.status === 'done' ? '✓' : f.status === 'failed' ? '✗' : '⏳'} {f.name}
                      </div>
                    ))}
                  </div>
                )}
              </>
            )}

            {/* ── Auto Tab ── */}
            {aiTab === 'auto' && (
              <>
                <div style={s.aiField}>
                  <label style={s.aiLabel}>Research Topic</label>
                  <input style={s.aiInput} value={autoTopic} onChange={e => setAutoTopic(e.target.value)} placeholder="e.g. Quantum computing" />
                </div>
                {!autoRunning ? (
                  <button style={{ ...s.aiBtn, background: '#dc2626' }} onClick={startAutoresearch} disabled={!autoTopic.trim() || aiLoading}>
                    ▶ Start Autoresearch
                  </button>
                ) : (
                  <button style={{ ...s.aiBtn, background: '#166534' }} onClick={stopAutoresearch}>
                    ⏹ Stop Autoresearch
                  </button>
                )}
                {autoStatus && <div style={{ fontSize: 11, color: '#fbbf24' }}>{autoStatus}</div>}
                <div style={s.aiHint}>Generates new wiki sections every 30 seconds while running.</div>
              </>
            )}
          </div>
        )}
      </aside>
    </div>
  );
}

/* ─── Styles ─── */
const s = {
  layout: { display: 'flex', height: '100vh', background: '#0f0f1a', color: '#e2e2e2', fontFamily: 'system-ui, -apple-system, sans-serif', overflow: 'hidden' },

  sidebar: { width: 240, minWidth: 240, background: '#12121c', borderRight: '1px solid #1e1e2e', display: 'flex', flexDirection: 'column', overflow: 'hidden' },
  sidebarHeader: { padding: '14px 16px', borderBottom: '1px solid #1e1e2e', display: 'flex', alignItems: 'center' },
  logo: { fontSize: 15, fontWeight: 700, color: '#f8fafc' },
  backBtn: { margin: '8px 12px 0', padding: '6px 10px', background: '#1e1e2e', color: '#94a3b8', border: '1px solid #2e2e3e', borderRadius: 4, fontSize: 12, cursor: 'pointer', textAlign: 'left' },
  searchBox: { padding: '10px 12px' },
  searchInput: { width: '100%', background: '#0a0a14', border: '1px solid #1e1e2e', borderRadius: 5, padding: '6px 10px', color: '#e2e2e2', fontSize: 13, outline: 'none' },
  navHeader: { padding: '8px 14px 4px', fontSize: 10, fontWeight: 700, textTransform: 'uppercase', letterSpacing: 0.8, color: '#64748b' },
  nav: { flex: 1, overflowY: 'auto', padding: '0 8px 8px' },
  navCategory: { padding: '8px 6px 2px', fontSize: 10, fontWeight: 600, textTransform: 'uppercase', letterSpacing: 0.6, color: '#64748b', borderTop: '1px solid #1e1e2e', marginTop: 4 },
  navItem: { display: 'flex', alignItems: 'center', gap: 8, padding: '5px 8px', borderRadius: 4, cursor: 'pointer', fontSize: 13, color: '#94a3b8', transition: 'background 0.15s' },
  navItemActive: { display: 'flex', alignItems: 'center', gap: 8, padding: '5px 8px', borderRadius: 4, cursor: 'pointer', fontSize: 13, color: '#e2e2e2', background: '#1e1e2e' },
  navIcon: { fontSize: 12, opacity: 0.7 },
  navTitle: { whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' },
  emptyNav: { padding: '20px 12px', fontSize: 12, color: '#64748b', textAlign: 'center', lineHeight: 1.6 },
  sidebarFooter: { padding: '10px 12px', borderTop: '1px solid #1e1e2e' },
  newPageBtn: { width: '100%', padding: '7px 0', background: '#1e1e2e', color: '#94a3b8', border: '1px solid #2e2e3e', borderRadius: 5, fontSize: 12, cursor: 'pointer' },

  main: { flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden', minWidth: 0 },

  toolbar: { display: 'flex', alignItems: 'center', gap: 8, padding: '8px 14px', background: '#12121c', borderBottom: '1px solid #1e1e2e', flexShrink: 0 },
  toolbarGroup: { display: 'flex', alignItems: 'center', gap: 4 },
  toolbarBtn: { padding: '4px 10px', background: '#1e1e2e', color: '#94a3b8', border: '1px solid #2e2e3e', borderRadius: 4, fontSize: 11, cursor: 'pointer' },
  modeBtn: { padding: '4px 12px', background: 'transparent', color: '#64748b', border: '1px solid transparent', borderRadius: 4, fontSize: 12, cursor: 'pointer' },
  modeBtnActive: { padding: '4px 12px', background: '#1e1e2e', color: '#e2e2e2', border: '1px solid #2e2e3e', borderRadius: 4, fontSize: 12, cursor: 'pointer' },

  editorPane: { flex: 1, display: 'flex', overflow: 'hidden', position: 'relative' },
  full: { flex: 1, overflow: 'auto' },
  splitLeft: { width: '50%', overflow: 'auto', borderRight: '1px solid #1e1e2e' },
  splitRight: { flex: 1, overflow: 'auto', display: 'flex' },

  textarea: { width: '100%', height: '100%', background: '#0a0a14', border: 'none', padding: '16px 20px', color: '#e2e2e2', fontSize: 14, lineHeight: 1.7, fontFamily: 'ui-monospace, SFMono-Regular, monospace', resize: 'none', outline: 'none' },
  preview: { flex: 1, padding: '16px 24px', fontSize: 14, lineHeight: 1.7, overflow: 'auto' },

  toc: { width: 200, minWidth: 200, padding: '16px 14px', borderLeft: '1px solid #1e1e2e', background: '#12121c', fontSize: 12 },
  tocTitle: { fontWeight: 700, color: '#94a3b8', marginBottom: 8, fontSize: 11, textTransform: 'uppercase', letterSpacing: 0.5 },
  tocItem: { padding: '3px 0', color: '#94a3b8', cursor: 'pointer' },
  tocItem3: { padding: '3px 0 3px 12px', color: '#64748b', cursor: 'pointer' },

  aiPanel: { width: 360, minWidth: 360, background: '#12121c', borderLeft: '1px solid #1e1e2e', display: 'flex', flexDirection: 'column', overflow: 'hidden' },
  aiPanelCollapsed: { width: 36, minWidth: 36, background: '#12121c', borderLeft: '1px solid #1e1e2e', display: 'flex', flexDirection: 'column', overflow: 'hidden' },
  aiHeader: { padding: '12px 14px', borderBottom: '1px solid #1e1e2e', display: 'flex', alignItems: 'center', justifyContent: 'space-between', cursor: 'pointer', userSelect: 'none' },
  aiToggle: { fontSize: 16, color: '#64748b' },
  aiBody: { flex: 1, overflowY: 'auto', padding: '12px 14px', display: 'flex', flexDirection: 'column', gap: 12 },
  aiField: { display: 'flex', flexDirection: 'column', gap: 5 },
  aiLabel: { fontSize: 10, color: '#64748b', textTransform: 'uppercase', letterSpacing: 0.6, fontWeight: 600 },
  aiTextarea: { background: '#0a0a14', border: '1px solid #1e1e2e', borderRadius: 5, padding: '8px 10px', color: '#e2e2e2', fontSize: 13, resize: 'vertical', outline: 'none', fontFamily: 'inherit' },
  aiInput: { background: '#0a0a14', border: '1px solid #1e1e2e', borderRadius: 5, padding: '7px 10px', color: '#e2e2e2', fontSize: 13, outline: 'none' },
  aiBtn: { background: '#3b82f6', color: '#fff', border: 'none', padding: '8px 14px', borderRadius: 5, fontSize: 13, cursor: 'pointer', marginTop: 4 },
  aiHint: { fontSize: 11, color: '#64748b', lineHeight: 1.5, marginTop: 4 },

  tabBtn: { padding: '4px 8px', background: '#1e1e2e', color: '#94a3b8', border: '1px solid #2e2e3e', borderRadius: 4, fontSize: 10, cursor: 'pointer', whiteSpace: 'nowrap' },
  tabBtnActive: { background: '#0a0a14', color: '#e2e2e2', border: '1px solid #3e3e4e' },

  miniBtn: { padding: '5px 8px', background: '#1e1e2e', color: '#94a3b8', border: '1px solid #2e2e3e', borderRadius: 4, fontSize: 11, cursor: 'pointer', textAlign: 'left' },

  inlineBtn: { padding: '4px 8px', background: '#2e2e3e', color: '#e2e2e2', border: '1px solid #3e3e4e', borderRadius: 4, fontSize: 11, cursor: 'pointer', whiteSpace: 'nowrap' },
};
